/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConfirmationNotificationsModel } from '../models/ConfirmationNotificationsModel';
import { ReminderNotificationsModel } from '../models/ReminderNotificationsModel';
import { HttpFile } from '../http/http';

export class BookingNotificationsModel {
    'confirmation'?: ConfirmationNotificationsModel;
    'reminders'?: Set<ReminderNotificationsModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "confirmation",
            "baseName": "confirmation",
            "type": "ConfirmationNotificationsModel",
            "format": ""
        },
        {
            "name": "reminders",
            "baseName": "reminders",
            "type": "Set<ReminderNotificationsModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BookingNotificationsModel.attributeTypeMap;
    }

    public constructor() {
    }
}

