/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicBookingModel } from '../models/PublicBookingModel';
import { HttpFile } from '../http/http';

export class BookingsList {
    'bookings': Array<PublicBookingModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bookings",
            "baseName": "bookings",
            "type": "Array<PublicBookingModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BookingsList.attributeTypeMap;
    }

    public constructor() {
    }
}

