/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Not null if the booking has been cancelled.
*/
export class CancellationModel {
    'cancelledBy': CancellationModelCancelledByEnum;
    'cancelledAt': Date;
    'reason'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cancelledBy",
            "baseName": "cancelledBy",
            "type": "CancellationModelCancelledByEnum",
            "format": ""
        },
        {
            "name": "cancelledAt",
            "baseName": "cancelledAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CancellationModel.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CancellationModelCancelledByEnum {
    Organizer = 'ORGANIZER',
    Booker = 'BOOKER'
}

