/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvaluatedTimeSlotModel } from '../models/EvaluatedTimeSlotModel';
import { EventTypeQuestion } from '../models/EventTypeQuestion';
import { HttpFile } from '../http/http';

export class EventTypeAvailabilityModel {
    'id': string;
    'name': string;
    'description'?: string;
    'questions': Array<EventTypeQuestion>;
    'timeSlots': Array<EvaluatedTimeSlotModel>;
    'imageUrl'?: string;
    'maxConcurrentBookings'?: number;
    'availableUnits'?: number;
    'maxUnitsPerBooking'?: number;
    'unitsLabel'?: string;
    'eventTypeTimeZone'?: string;
    'eventTypeTags': { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "questions",
            "baseName": "questions",
            "type": "Array<EventTypeQuestion>",
            "format": ""
        },
        {
            "name": "timeSlots",
            "baseName": "timeSlots",
            "type": "Array<EvaluatedTimeSlotModel>",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "maxConcurrentBookings",
            "baseName": "maxConcurrentBookings",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "availableUnits",
            "baseName": "availableUnits",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maxUnitsPerBooking",
            "baseName": "maxUnitsPerBooking",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "unitsLabel",
            "baseName": "unitsLabel",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventTypeTimeZone",
            "baseName": "eventTypeTimeZone",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventTypeTags",
            "baseName": "eventTypeTags",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventTypeAvailabilityModel.attributeTypeMap;
    }

    public constructor() {
    }
}

