/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventTypeListItem } from '../models/EventTypeListItem';
import { HttpFile } from '../http/http';

export class EventTypesListBody {
    'eventTypes': Array<EventTypeListItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "eventTypes",
            "baseName": "eventTypes",
            "type": "Array<EventTypeListItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventTypesListBody.attributeTypeMap;
    }

    public constructor() {
    }
}

