/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExternalBookingAnsweredQuestionModel } from '../models/ExternalBookingAnsweredQuestionModel';
import { ExternalBookingEventTypeModel } from '../models/ExternalBookingEventTypeModel';
import { ExternalBookingEventTypeOwnerModel } from '../models/ExternalBookingEventTypeOwnerModel';
import { InstantInterval } from '../models/InstantInterval';
import { HttpFile } from '../http/http';

export class ExternalBookingValidationModel {
    'id': string;
    'eventType': ExternalBookingEventTypeModel;
    'eventTypeOwner': ExternalBookingEventTypeOwnerModel;
    'interval': InstantInterval;
    'answeredQuestions': Array<ExternalBookingAnsweredQuestionModel>;
    /**
    * Booked units.
    */
    'units'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "ExternalBookingEventTypeModel",
            "format": ""
        },
        {
            "name": "eventTypeOwner",
            "baseName": "eventTypeOwner",
            "type": "ExternalBookingEventTypeOwnerModel",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "InstantInterval",
            "format": ""
        },
        {
            "name": "answeredQuestions",
            "baseName": "answeredQuestions",
            "type": "Array<ExternalBookingAnsweredQuestionModel>",
            "format": ""
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return ExternalBookingValidationModel.attributeTypeMap;
    }

    public constructor() {
    }
}

