/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstantInterval } from '../models/InstantInterval';
import { UsedBookingResource } from '../models/UsedBookingResource';
import { HttpFile } from '../http/http';

export class ExternalBooking {
    'eventTypeId': string;
    'interval': InstantInterval;
    'bookerEmail'?: string;
    'answers'?: { [key: string]: string; };
    'notes'?: string;
    'units'?: number;
    'resources'?: Set<UsedBookingResource>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "eventTypeId",
            "baseName": "eventTypeId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "InstantInterval",
            "format": ""
        },
        {
            "name": "bookerEmail",
            "baseName": "bookerEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "answers",
            "baseName": "answers",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Set<UsedBookingResource>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExternalBooking.attributeTypeMap;
    }

    public constructor() {
    }
}

