/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LocationModel } from '../models/LocationModel';
import { HttpFile } from '../http/http';

export class FixedLocation extends LocationModel {
    'freeText': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "freeText",
            "baseName": "freeText",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(FixedLocation.attributeTypeMap);
    }

    public constructor() {
        super();
        this.type = "FixedLocation";
    }
}

