/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserModel } from '../models/UserModel';
import { HttpFile } from '../http/http';

export class ListUsersResponse {
    'users': Array<UserModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<UserModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListUsersResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

