/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MaxBookingsPerTimeUnit {
    /**
    * Max bookings allowed per natural hour.
    */
    'perHour'?: number;
    /**
    * Max bookings allowed per natural day. The start of the day is calculated considering the event & user\'s timezone.
    */
    'perDay'?: number;
    /**
    * Max bookings per natural week. Starting on Monday, and the the starting hour is calculated considering the event & user\'s timezone.
    */
    'perWeek'?: number;
    /**
    * Max bookings per natural month. The the starting hour for the first day of the month is calculated considering the event & user\'s timezone.
    */
    'perMonth'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "perHour",
            "baseName": "perHour",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "perDay",
            "baseName": "perDay",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "perWeek",
            "baseName": "perWeek",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "perMonth",
            "baseName": "perMonth",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return MaxBookingsPerTimeUnit.attributeTypeMap;
    }

    public constructor() {
    }
}

