/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LocationModel } from '../models/LocationModel';
import { HttpFile } from '../http/http';

export class MicrosoftOutlookLocation extends LocationModel {

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MicrosoftOutlookLocation.attributeTypeMap);
    }

    public constructor() {
        super();
        this.type = "MicrosoftOutlookLocation";
    }
}

