/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrganizationMembership {
    'organizationId': string;
    'roles': Set<OrganizationMembershipRolesEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Set<OrganizationMembershipRolesEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationMembership.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum OrganizationMembershipRolesEnum {
    Member = 'MEMBER',
    Admin = 'ADMIN'
}

