/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Organization } from '../models/Organization';
import { HttpFile } from '../http/http';

export class OrganizationsList {
    'organizations': Array<Organization>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<Organization>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationsList.attributeTypeMap;
    }

    public constructor() {
    }
}

