/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrganizationMember } from '../models/OrganizationMember';
import { HttpFile } from '../http/http';

export class OrganizationMembersList {
    'members': Array<OrganizationMember>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<OrganizationMember>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationMembersList.attributeTypeMap;
    }

    public constructor() {
    }
}

