/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventTypeQuestion } from '../models/EventTypeQuestion';
import { HttpFile } from '../http/http';

export class PasswordQuestion extends EventTypeQuestion {
    'canBeDeleted'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "canBeDeleted",
            "baseName": "canBeDeleted",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PasswordQuestion.attributeTypeMap);
    }

    public constructor() {
        super();
        this.type = "PasswordQuestion";
    }
}

