/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnsweredQuestionModel } from '../models/AnsweredQuestionModel';
import { BookedEventTypeModel } from '../models/BookedEventTypeModel';
import { BookedResourceModel } from '../models/BookedResourceModel';
import { BookerModel } from '../models/BookerModel';
import { CancellationModel } from '../models/CancellationModel';
import { InstantInterval } from '../models/InstantInterval';
import { HttpFile } from '../http/http';

export class PublicBookingModel {
    'id': string;
    'eventType': BookedEventTypeModel;
    'interval': InstantInterval;
    'booker': BookerModel;
    'answeredQuestions': Array<AnsweredQuestionModel>;
    /**
    * Additional notes added by the booker when submitting the booking.
    */
    'notes'?: string;
    /**
    * Booked units.
    */
    'units'?: number;
    'cancellation'?: CancellationModel;
    'bookedResources': Set<BookedResourceModel>;
    'conferenceLink'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "BookedEventTypeModel",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "InstantInterval",
            "format": ""
        },
        {
            "name": "booker",
            "baseName": "booker",
            "type": "BookerModel",
            "format": ""
        },
        {
            "name": "answeredQuestions",
            "baseName": "answeredQuestions",
            "type": "Array<AnsweredQuestionModel>",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "cancellation",
            "baseName": "cancellation",
            "type": "CancellationModel",
            "format": ""
        },
        {
            "name": "bookedResources",
            "baseName": "bookedResources",
            "type": "Set<BookedResourceModel>",
            "format": ""
        },
        {
            "name": "conferenceLink",
            "baseName": "conferenceLink",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return PublicBookingModel.attributeTypeMap;
    }

    public constructor() {
    }
}

