/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicProfile } from '../models/PublicProfile';
import { HttpFile } from '../http/http';

export class PublicProfilesList {
    'publicProfiles': Array<PublicProfile>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "publicProfiles",
            "baseName": "publicProfiles",
            "type": "Array<PublicProfile>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PublicProfilesList.attributeTypeMap;
    }

    public constructor() {
    }
}

