/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BookerPhoneLocation } from '../models/BookerPhoneLocation';
import { BookerSelectionLocation } from '../models/BookerSelectionLocation';
import { FixedLocation } from '../models/FixedLocation';
import { GoogleMeetLocation } from '../models/GoogleMeetLocation';
import { MicrosoftOutlookLocation } from '../models/MicrosoftOutlookLocation';
import { HttpFile } from '../http/http';

export class PutEventTypeModelLocation {
    'type': string;
    'questionId': string;
    'freeText': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "questionId",
            "baseName": "questionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "freeText",
            "baseName": "freeText",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PutEventTypeModelLocation.attributeTypeMap;
    }

    public constructor() {
    }
}

