/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmailQuestion } from '../models/EmailQuestion';
import { ImageQuestion } from '../models/ImageQuestion';
import { LocationOptionModel } from '../models/LocationOptionModel';
import { LocationQuestion } from '../models/LocationQuestion';
import { PasswordQuestion } from '../models/PasswordQuestion';
import { PhoneQuestion } from '../models/PhoneQuestion';
import { TextQuestion } from '../models/TextQuestion';
import { HttpFile } from '../http/http';

export class PutEventTypeModelQuestionsInner {
    'id': string;
    'label': string;
    'required'?: boolean;
    'canBeDeleted'?: boolean;
    'type': string;
    'allowedOptions': Set<LocationOptionModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canBeDeleted",
            "baseName": "canBeDeleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "allowedOptions",
            "baseName": "allowedOptions",
            "type": "Set<LocationOptionModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PutEventTypeModelQuestionsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

