/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PutProfileBody {
    'slug': string;
    'timeZone': string;
    'locale': PutProfileBodyLocaleEnum;
    'clientState'?: string;
    'tags'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "string",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "PutProfileBodyLocaleEnum",
            "format": ""
        },
        {
            "name": "clientState",
            "baseName": "clientState",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PutProfileBody.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PutProfileBodyLocaleEnum {
    EnUs = 'en-US',
    EsEs = 'es-ES'
}

