/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeRange } from '../models/TimeRange';
import { HttpFile } from '../http/http';

export class RepeatingAvailabilityModel {
    'timeZone': string;
    'weekly': { [key: string]: Set<TimeRange>; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "string",
            "format": ""
        },
        {
            "name": "weekly",
            "baseName": "weekly",
            "type": "{ [key: string]: Set<TimeRange>; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RepeatingAvailabilityModel.attributeTypeMap;
    }

    public constructor() {
    }
}

