/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Resource } from '../models/Resource';
import { HttpFile } from '../http/http';

export class ResourcesList {
    'resources': Set<Resource>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Set<Resource>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResourcesList.attributeTypeMap;
    }

    public constructor() {
    }
}

