/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvailableInGroupRule } from '../models/AvailableInGroupRule';
import { ResourceId } from '../models/ResourceId';
import { HttpFile } from '../http/http';

export class ResourceRules {
    'availableInGroups'?: Set<AvailableInGroupRule>;
    /**
    * Linked resources are useful to specify dependencies among different resources/event types. When linked resources are configured, the availability of those will be taken into account for the event type availability check. Also, when a booking is performed, these linked resources will be booked as well
    */
    'linkedResources'?: Set<ResourceId>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "availableInGroups",
            "baseName": "availableInGroups",
            "type": "Set<AvailableInGroupRule>",
            "format": ""
        },
        {
            "name": "linkedResources",
            "baseName": "linkedResources",
            "type": "Set<ResourceId>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResourceRules.attributeTypeMap;
    }

    public constructor() {
    }
}

