/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResourceGroupModel } from '../models/ResourceGroupModel';
import { HttpFile } from '../http/http';

export class ResourceGroupsListModel {
    'resourceGroups': Set<ResourceGroupModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "resourceGroups",
            "baseName": "resourceGroups",
            "type": "Set<ResourceGroupModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResourceGroupsListModel.attributeTypeMap;
    }

    public constructor() {
    }
}

