/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ThirdPartyConsentBody {
    'authCode': string;
    'provider': ThirdPartyConsentBodyProviderEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "authCode",
            "baseName": "authCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "ThirdPartyConsentBodyProviderEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ThirdPartyConsentBody.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ThirdPartyConsentBodyProviderEnum {
    Microsoft = 'MICROSOFT'
}

