/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstantInterval } from '../models/InstantInterval';
import { ThirdPartyCalendarModel } from '../models/ThirdPartyCalendarModel';
import { HttpFile } from '../http/http';

export class ThirdPartyCalendarEvent {
    'calendar': ThirdPartyCalendarModel;
    'interval': InstantInterval;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "calendar",
            "baseName": "calendar",
            "type": "ThirdPartyCalendarModel",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "InstantInterval",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ThirdPartyCalendarEvent.attributeTypeMap;
    }

    public constructor() {
    }
}

