/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ThirdPartyCalendarEvent } from '../models/ThirdPartyCalendarEvent';
import { HttpFile } from '../http/http';

export class ThirdPartyCalendarEventsList {
    'events': Array<ThirdPartyCalendarEvent>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<ThirdPartyCalendarEvent>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ThirdPartyCalendarEventsList.attributeTypeMap;
    }

    public constructor() {
    }
}

