/**
 * timetime
 * timetime API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrganizationMembership } from '../models/OrganizationMembership';
import { TenantMembershipModel } from '../models/TenantMembershipModel';
import { ThirdPartyCalendarModel } from '../models/ThirdPartyCalendarModel';
import { HttpFile } from '../http/http';

export class UserModel {
    'userId': string;
    'slug': string;
    'timeZone': string;
    'locale': UserModelLocaleEnum;
    'thirdPartyCalendars': Array<ThirdPartyCalendarModel>;
    'clientState': string;
    'email': string;
    'tenant': TenantMembershipModel;
    'tags': { [key: string]: string; };
    'organizationMemberships': Set<OrganizationMembership>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "string",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "UserModelLocaleEnum",
            "format": ""
        },
        {
            "name": "thirdPartyCalendars",
            "baseName": "thirdPartyCalendars",
            "type": "Array<ThirdPartyCalendarModel>",
            "format": ""
        },
        {
            "name": "clientState",
            "baseName": "clientState",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "tenant",
            "baseName": "tenant",
            "type": "TenantMembershipModel",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "organizationMemberships",
            "baseName": "organizationMemberships",
            "type": "Set<OrganizationMembership>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserModel.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserModelLocaleEnum {
    EnUs = 'en-US',
    EsEs = 'es-ES'
}

